#!/usr/bin/env ts-node
/**
 * Cletus Staking Contract - Initialization Script
 *
 * Initializes the staking program after deployment:
 * - Creates global state PDA
 * - Creates rewards pool PDA
 * - Sets admin and multisig signers
 * - Funds initial rewards pool
 *
 * Usage:
 *   NETWORK=devnet \
 *   ADMIN_WALLET=<pubkey> \
 *   MULTISIG_1=<pubkey> \
 *   MULTISIG_2=<pubkey> \
 *   MULTISIG_3=<pubkey> \
 *   INITIAL_FUNDING=2.0 \
 *   ts-node staking-contract/scripts/initialize.ts
 */

import * as anchor from '@coral-xyz/anchor';
import { Program, AnchorProvider, Wallet } from '@coral-xyz/anchor';
import {
  PublicKey,
  Keypair,
  Connection,
  clusterApiUrl,
  LAMPORTS_PER_SOL,
} from '@solana/web3.js';
import * as fs from 'fs';
import * as path from 'path';

// ============================================================
// Configuration
// ============================================================

const NETWORK = (process.env.NETWORK as 'devnet' | 'mainnet-beta') || 'devnet';
const PROGRAM_ID = 'CLETUSxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'; // Replace after deployment

// Admin and multisig configuration
const ADMIN_WALLET =
  process.env.ADMIN_WALLET || '9xQeKq6isj8Xu26Ku2b3FqxZsEaq5XfVhJ5dNon9Mop7';
const MULTISIG_1 = process.env.MULTISIG_1 || ADMIN_WALLET;
const MULTISIG_2 = process.env.MULTISIG_2 || '';
const MULTISIG_3 = process.env.MULTISIG_3 || '';

// Initial SOL funding for rewards pool (in SOL)
const INITIAL_FUNDING_SOL = parseFloat(process.env.INITIAL_FUNDING || '1.0');

// ============================================================
// Main Initialization
// ============================================================

async function initialize() {
  console.log('\n🔧 Cletus Staking - Initialization Script');
  console.log('==========================================');
  console.log(`Network:         ${NETWORK}`);
  console.log(`Admin:           ${ADMIN_WALLET}`);
  console.log(`Multisig 1:      ${MULTISIG_1}`);
  console.log(`Multisig 2:      ${MULTISIG_2 || '(not set)'}`);
  console.log(`Multisig 3:      ${MULTISIG_3 || '(not set)'}`);
  console.log(`Initial Funding: ${INITIAL_FUNDING_SOL} SOL`);

  // Validation
  if (!MULTISIG_2 || !MULTISIG_3) {
    console.error('\n❌ All 3 multisig signer addresses are required for security.');
    console.error('Set: MULTISIG_1, MULTISIG_2, MULTISIG_3 environment variables');
    process.exit(1);
  }

  // Load deployer wallet
  const walletPath =
    process.env.WALLET_PATH || path.join(process.env.HOME || '~', '.config/solana/id.json');

  if (!fs.existsSync(walletPath)) {
    console.error(`\n❌ Wallet not found at: ${walletPath}`);
    process.exit(1);
  }

  const walletKeyData = JSON.parse(fs.readFileSync(walletPath, 'utf-8'));
  const deployer = Keypair.fromSecretKey(Uint8Array.from(walletKeyData));

  console.log(`\n📋 Deployer: ${deployer.publicKey.toBase58()}`);

  // Connect
  const rpcUrl = process.env.RPC_URL || clusterApiUrl(NETWORK);
  const connection = new Connection(rpcUrl, 'confirmed');

  const balance = await connection.getBalance(deployer.publicKey);
  console.log(`💰 Balance: ${(balance / LAMPORTS_PER_SOL).toFixed(4)} SOL`);

  const requiredSol = INITIAL_FUNDING_SOL + 0.05; // Extra for tx fees
  if (balance < requiredSol * LAMPORTS_PER_SOL) {
    console.error(`\n❌ Insufficient balance. Need at least ${requiredSol} SOL`);
    process.exit(1);
  }

  // Setup Anchor provider
  const wallet = new Wallet(deployer);
  const provider = new AnchorProvider(connection, wallet, {
    commitment: 'confirmed',
  });
  anchor.setProvider(provider);

  // Load IDL (generated by anchor build)
  const idlPath = path.join(
    __dirname,
    '../target/idl/cletus_staking.json'
  );

  if (!fs.existsSync(idlPath)) {
    console.error('\n❌ IDL not found. Run: anchor build first');
    console.log('Then re-run this script.');

    // Show what the initialization would do
    console.log('\n📝 Initialization preview (will execute after build):');
    console.log('  1. Create GlobalState PDA');
    console.log('  2. Create RewardsPool PDA');
    console.log('  3. Set admin and multisig signers');
    console.log(`  4. Fund rewards pool with ${INITIAL_FUNDING_SOL} SOL`);
    return;
  }

  const idl = JSON.parse(fs.readFileSync(idlPath, 'utf-8'));
  const programId = new PublicKey(PROGRAM_ID);
  const program = new Program(idl, programId, provider);

  // Derive PDAs
  const [globalStatePda, globalStateBump] = PublicKey.findProgramAddressSync(
    [Buffer.from('global_state')],
    programId
  );

  const [rewardsPoolPda] = PublicKey.findProgramAddressSync(
    [Buffer.from('rewards_pool')],
    programId
  );

  console.log('\n📍 PDAs:');
  console.log(`  Global State:  ${globalStatePda.toBase58()} (bump: ${globalStateBump})`);
  console.log(`  Rewards Pool:  ${rewardsPoolPda.toBase58()}`);

  // Check if already initialized
  const existingState = await connection.getAccountInfo(globalStatePda);
  if (existingState) {
    console.log('\n⚠️  Program already initialized.');
    console.log('   Global state account exists. Skipping initialization.');
    await fundRewardsPool(program, rewardsPoolPda, deployer, INITIAL_FUNDING_SOL);
    return;
  }

  // Initialize the program
  console.log('\n🚀 Initializing program...');

  try {
    const adminPubkey = new PublicKey(ADMIN_WALLET);
    const multisigSigners: [PublicKey, PublicKey, PublicKey] = [
      new PublicKey(MULTISIG_1),
      new PublicKey(MULTISIG_2),
      new PublicKey(MULTISIG_3),
    ];

    const tx = await (program.methods as Record<string, Function>)
      .initialize(adminPubkey, multisigSigners)
      .accounts({
        globalState: globalStatePda,
        rewardsPool: rewardsPoolPda,
        payer: deployer.publicKey,
        systemProgram: anchor.web3.SystemProgram.programId,
      })
      .rpc();

    console.log(`✅ Initialized! TX: ${tx}`);
    console.log(
      `   Explorer: https://explorer.solana.com/tx/${tx}?cluster=${NETWORK}`
    );
  } catch (err) {
    console.error('\n❌ Initialization failed:', err);
    process.exit(1);
  }

  // Fund rewards pool
  await fundRewardsPool(program, rewardsPoolPda, deployer, INITIAL_FUNDING_SOL);

  // Save deployment info
  const deployInfo = {
    network: NETWORK,
    programId: PROGRAM_ID,
    globalState: globalStatePda.toBase58(),
    rewardsPool: rewardsPoolPda.toBase58(),
    admin: ADMIN_WALLET,
    multisigSigners: [MULTISIG_1, MULTISIG_2, MULTISIG_3],
    deployedAt: new Date().toISOString(),
  };

  const deployInfoPath = path.join(__dirname, '../deployment-info.json');
  fs.writeFileSync(deployInfoPath, JSON.stringify(deployInfo, null, 2));
  console.log(`\n📄 Deployment info saved to: ${deployInfoPath}`);

  console.log('\n🎉 Cletus Staking Program initialized successfully!');
  console.log('\n📝 Next steps:');
  console.log('  1. Create CLETUS token mint (if not done)');
  console.log('  2. Create staking vault token account');
  console.log('  3. Update frontend with program ID and PDAs');
  console.log('  4. Test stake/unstake on devnet');
  console.log('  5. Audit before mainnet deployment');
}

async function fundRewardsPool(
  program: Program,
  rewardsPoolPda: PublicKey,
  funder: Keypair,
  amountSol: number
) {
  console.log(`\n💧 Funding rewards pool with ${amountSol} SOL...`);

  try {
    const amountLamports = Math.floor(amountSol * LAMPORTS_PER_SOL);
    const tx = await (program.methods as Record<string, Function>)
      .fundRewardsPool(new anchor.BN(amountLamports))
      .accounts({
        rewardsPool: rewardsPoolPda,
        funder: funder.publicKey,
        systemProgram: anchor.web3.SystemProgram.programId,
      })
      .rpc();

    console.log(`✅ Rewards pool funded! TX: ${tx}`);
  } catch (err) {
    console.error('⚠️  Failed to fund rewards pool:', err);
    console.log('   You can fund manually later with: fund-rewards command');
  }
}

initialize().catch(console.error);
